booted_cmds:
  names:
  - setup_tf
  - Voxel Grid
  - Ray Ground
  - NDT Mapping
lane_select:
  distance_threshold_neighbor_lanes: 5.0
  enablePlannerDynamicSwitch: false
  lane_change_interval: 10.0
  lane_change_target_minimum: 10.0
  lane_change_target_ratio: 5.0
  vector_length_hermite_curve: 10.0
ndt_mapping:
  imu_topic: !!python/unicode '/imu_raw'
  imu_upside_down: false
  incremental_voxel_update: false
  leaf_size: 1.0
  max_iterations: 30
  max_scan_range: 200.0
  method_type: 0
  min_add_scan_shift: 1.0
  min_scan_range: 5.0
  resolution: 1.0
  step_size: 0.1
  trans_epsilon: 0.01
  use_imu: false
  use_odom: false
ndt_matching:
  error_threshold: 1.0
  get_height: false
  imu_topic: !!python/unicode '/imu_raw'
  imu_upside_down: false
  init_pos_gnss: 0
  max_iterations: 30
  method_type: 0
  output_log_data: false
  pitch: 0.0
  resolution: 1.0
  roll: 0.0
  step_size: 0.1
  sync: false
  trans_epsilon: 0.01
  use_imu: false
  use_odom: false
  use_predict_pose: 1
  x: 0.0
  y: 0.0
  yaw: 0.0
  z: 0.0
obstacle_avoid:
  avoid_distance: 13.0
  avoid_velocity_limit_mps: 4.0
  avoidance: false
pcd:
  pcd_file: ''
play_rosbag_play:
  file: ''
  rate: ''
  repeat: false
  start: 0
point_cloud:
  path_area_list: None
  path_area_list_cmd_param: null
  path_pcd: ''
  scene_num: noupdate
pure_pursuit:
  displacement_threshold: 0.0
  is_linear_interpolation: true
  lookahead_distance: 4.0
  lookahead_ratio: 2.0
  minimum_lookahead_distance: 6.0
  param_flag: 1
  publishes_for_steering_robot: false
  relative_angle_threshold: 0
  velocity: 5.0
ray_ground_filter:
  clipping_height: 0.2
  concentric_divider_distance: 0.01
  general_max_slope: 5
  input_point_topic: /points_raw
  local_max_slope: 8
  min_height_threshold: 0.05
  min_point_distance: 1.85
  radial_divider_angle: 0.08
  reclass_distance_threshold: 0.2
  sensor_height: 1.8
sd_vehicle_interface:
  param: 0.0
setup_tf:
  frame_id: /base_link
  localizer_cmd_param: /velodyne
  localizer_rosparam: velodyne
  period_in_ms: 10
  pitch: 0.0
  roll: 0.0
  x: 0.68
  y: 0.0
  yaw: 0.0
  z: 1.445
setup_tf_1:
  file: ''
tf:
  file: ''
traffic_waypoints:
  acceleration: 1.0
  number_of_smoothing_count: 0
  number_of_zeros_ahead: 0
  number_of_zeros_behind: 0
  stopline_search_radius: 1.0
twist_filter:
  lateral_accel_limit: 0.8
  lowpass_gain_angular_z: 0.0
  lowpass_gain_linear_x: 0.0
twizy_sim:
  enable_rviz: true
  world_cmd_param: default
vehicle_info:
  info_path: ''
vehicle_interface:
  ins_cmd_param: oxts
  mode_cmd_param: false
  speed_input_cmd_param: vehicle_can_speed
  vehicle_cmd_param: env200
vehicle_model:
  file: ''
  model_path: ''
  vehicle_model_cmd_param: sd_twizy
velocity_set:
  deceleration_obstacle: 0.7
  deceleration_range: 0
  deceleration_stopline: 0.3
  detection_height_bottom: -1.5
  detection_height_top: 0.1
  detection_range: 1.3
  enablePlannerDynamicSwitch: false
  enable_multiple_crosswalk_detection: false
  points_topic: points_no_ground
  radar_threshold_points: 1
  stop_distance_obstacle: 15.0
  stop_distance_stopline: 5.0
  temporal_waypoints_size: 100.0
  threshold_points: 5
  use_crosswalk_detection: false
  velocity_change_limit: 7.0
voxel_grid_filter:
  measurement_range: 200
  points_topic: /points_raw
  sync: false
  voxel_leaf_size: 2.0
waypoint_loader:
  accel_limit: 0.98
  decel_limit: 0.98
  disable_decision_maker: true
  end_point_offset: 5
  multi_lane_csv: ''
  radius_min: 6.0
  radius_thresh: 20.0
  replanning_mode: false
  resample_interval: 1.0
  resample_mode: true
  velocity_max: 20.0
  velocity_min: 4.0
  velocity_offset: 4
