##########################################
################## GOAL ##################
##########################################

# Flag which indicates if the exposure times are provided and hence should be
# set before grabbing
bool exposure_given

# The list of target exposure time in microseconds.
# It is possible to grab only one image as well as several images with
# different exposure times. This values can be overriden from the brightness
# search, in case that the flag exposure_fixed is not true.
# The interface will only try to set these values if the exposure_given flag is
# set to true.
float32[] exposure_times

# If the exposure_fixed flag is set, the exposure time will stay fix in
# case of a brightness search. Hence the target brightness will be reached
# only by varying the gain
bool exposure_fixed


# Flag which indicates if the brightness values are provided and hence should
# be set before grabbing
bool brightness_given

# The average intensity values of the images. It depends the exposure time
# as well as the gain setting. The interface will only try to reach this
# value if the brightness_given flag is set to true.
float32[] brightness_values

# The brightness_continuous flag controls the auto brightness function.
# If it is set to false, the given brightness will only be reached once.
# Hence changing light conditions lead to changing brightness values.
# If it is set to true, the given brightness will be reached continuously,
# trying to adapt to changing light conditions.
bool brightness_continuous


# Flag which indicates if the gain is provided and hence should be set before
# grabbing
bool gain_given

# The target gain values in percent of the maximal value the camera supports
# For USB-Cameras, the gain is in dB, for GigE-Cameras it is given in so
# called 'device specific units'. This value can be overriden from the
# brightness search, in case that the gain_fixed flag is set to false.
# The interface will only try to reach this values if the gain_given flag is
# set to true.
float32[] gain_values

# If the gain_fixed flag is set, the gain value will stay fix in
# case of a brightness search. Hence the target brightness will be reached
# only by varying the exposure
bool gain_fixed

# Flag which indicates if the gamma value is provided and hence should be set
# before grabbing
bool gamma_given

# Gamma correction of pixel intensity.
# Adjusts the brightness of the pixel values output by the camera's sensor
# to account for a non-linearity in the human perception of brightness or
# of the display system (such as CRT).
# The interface will only try to reach this value if the gamma_given flag is
# set to true.
float32[] gamma_values

---
##########################################
################# RESULT #################
##########################################

# The resulting HDR image generated out of several images with the inquired
# image intensity settings.
sensor_msgs/Image hdr_image

# The CameraInfo obejct describing the camera properties for the above image
# sequence. Static in many cases, but can also support variable binning setting
sensor_msgs/CameraInfo cam_info

# The reached values of the images e.g. the values that were set to the camera
# before the grab
float32[] reached_exposure_times

float32[] reached_brightness_values

float32[] reached_gain_values

float32[] reached_gamma_values

# Flag which indicates the success of the grabbing action
bool success

---
##########################################
################ FEEDBACK ################
##########################################
int32 curr_nr_images_taken
