# This service returns the current camera properties as well as the limits
---
bool success

bool is_sleeping

string device_user_id

int32 min_binning_x
int32 max_binning_x
int32 current_binning_x

int32 min_binning_y
int32 max_binning_y
int32 current_binning_y

float32 max_framerate
float32 current_framerate

float32 min_exposure
float32 max_exposure
float32 current_exposure

float32 min_gain_in_cam_units
float32 max_gain_in_cam_units
float32 current_gain_in_cam_units

float32 min_gain
float32 max_gain
float32 current_gain

float32 min_gamma
float32 max_gamma
float32 current_gamma

bool brightness_continuous
bool gain_auto
bool exposure_auto
