# The target exposure time measured in microseconds.
# If the limits were exceeded, the desired exposure time will be truncated.
float32 target_exposure
---
# Exact match can not always be reached
float32 reached_exposure
bool success
