# The target gain in percent of the maximal value the camera supports.
# For USB-Cameras, the gain is in dB, for GigE-Cameras it is given in so
# called 'device specific units'.
float32 target_gain
---
# Exact match can not always be reached
float32 reached_gain
bool success
