# If the camera runs in topic mode (continuously publishing images over the
# topics respecting the desired frame_rate) this service offers the posibillity
# to pause the image acquisition. To restart the grabbing, this service should
# be called again with set_sleeping set to false
bool set_sleeping
---
bool success
